image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - publish

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - echo "Building image"
    - docker build --tag api-fpl-net:latest .
    - docker save -o api-fpl-net.tar api-fpl-net:latest
  artifacts:
    paths:
      - api-fpl-net.tar

test:
  stage: test
  script:
    - echo "Running unit tests... NOT"

publish:
  stage: publish
  dependencies:
    - build
  script:
    - echo "Publishing image to gitlab registry"
    - docker load -i api-fpl-net.tar
    - docker tag api-fpl-net:latest registry.gitlab.com/msjp/api-fpl-net:latest
    - docker push registry.gitlab.com/msjp/api-fpl-net:latest
    - docker rmi api-fpl-net:latest